[package]
name = "rpg_tools_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.3"
rpg_tools_rendering = { path = "../rpg_tools_rendering" }
