[package]
name = "rpg_tools_rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rpg_tools_core = { path = "../rpg_tools_core" }